# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_enf', models.CharField(max_length=200)),
                ('link_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_sint', models.CharField(max_length=200)),
                ('link_desc', models.CharField(max_length=200)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Enfermedad')),
            ],
            options={
                'db_table': 'sintoma',
            },
        ),
    ]
